# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170120_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2017, 1, 20, 11, 21, 44, 441294, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
